spring:
  application:
    name: stockflowserver

  datasource:
    url: jdbc:postgresql://localhost:5432/stockflow
    username: stockflow_user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    enabled: true

server:
  port: 8080





